name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: trailofbits/slither-analyze-action@master
        with:
          target: 'test.sol'
